using QsEarlyWarning.Domain.Estimate;

namespace QsEarlyWarning.Infrastructure.Excel;

/// <summary>
/// Reads the authored IFC-element → BOQ-item register from its sidecar CSV.
///
/// <para><b>Why a sidecar and not a sheet.</b> The workbook is read-only source data. Adding a sheet
/// to it would fork the file we were handed from the one the rest of the pipeline — and its
/// row-count contract tests — are pinned to. A CSV beside it stays diffable in git, opens in the
/// same spreadsheet, and can be hand-edited by a QS who disagrees with a binding.</para>
///
/// <para>Generated by <c>tools/ifc_boq_map/generate_map.py</c>. Rows carrying no
/// <c>BoqItemRef</c> are the scope gap — elements the model contains and the bill prices nothing
/// for — and they are loaded, not skipped, because that absence is a finding.</para>
///
/// <para>Memoized and project-gated, mirroring <see cref="EstimateWorkbookLoader"/>: the register
/// binds one model to one bill, so any other project gets null and the feature is absent rather
/// than wrong. Load failures degrade to null for the same reason.</para>
/// </summary>
public sealed class IfcElementMapCsvLoader : IIfcElementMapSource
{
    private readonly string _csvPath;
    private readonly long? _owningProjectId;
    private readonly object _gate = new();
    private bool _attempted;
    private IfcElementMap? _cached;

    public IfcElementMapCsvLoader(string csvPath, long? owningProjectId)
    {
        _csvPath = csvPath;
        _owningProjectId = owningProjectId;
    }

    public IfcElementMap? TryLoadForProject(long projectId)
    {
        if (_owningProjectId is null || projectId != _owningProjectId) return null;

        lock (_gate)
        {
            if (_attempted) return _cached;
            _attempted = true;
            try { _cached = Load(_csvPath); }
            catch { _cached = null; }
            return _cached;
        }
    }

    /// <summary>Parses the register. Public so tests can read it without a project id.</summary>
    public static IfcElementMap Load(string csvPath)
    {
        var lines = File.ReadAllLines(csvPath);
        if (lines.Length < 2) throw new InvalidOperationException($"'{csvPath}' has no data rows.");

        var header = SplitCsv(lines[0]);
        int Col(string name)
        {
            var i = Array.FindIndex(header, h => string.Equals(h.Trim(), name, StringComparison.OrdinalIgnoreCase));
            if (i < 0) throw new InvalidOperationException($"'{csvPath}' is missing the '{name}' column.");
            return i;
        }

        int cGuid = Col("IfcGlobalId"), cClass = Col("IfcClass"), cStorey = Col("Storey");
        int cItem = Col("BoqItemRef"), cRole = Col("Role"), cBasis = Col("Basis"), cConf = Col("Confidence");

        // One element can own several rows (a slab is concrete AND its soffit formwork), so rows are
        // folded onto the element rather than each becoming one.
        var refsByGuid = new Dictionary<string, List<string>>(StringComparer.Ordinal);
        var elementMeta = new Dictionary<string, (string Cls, string? Storey, double Conf)>(StringComparer.Ordinal);
        var ruleCounts = new Dictionary<(string Cls, string Item), (string Role, string Basis, double Conf, int Count)>();
        var unmapped = new Dictionary<string, (int Count, string Reason)>(StringComparer.Ordinal);

        for (int i = 1; i < lines.Length; i++)
        {
            if (string.IsNullOrWhiteSpace(lines[i])) continue;
            var f = SplitCsv(lines[i]);
            if (f.Length <= cConf) continue;

            var guid = f[cGuid].Trim();
            if (guid.Length == 0) continue;

            var cls = f[cClass].Trim().ToUpperInvariant();
            var storey = f[cStorey].Trim();
            var itemRef = f[cItem].Trim();
            var basis = f[cBasis].Trim();
            double conf = double.TryParse(f[cConf], System.Globalization.NumberStyles.Float,
                System.Globalization.CultureInfo.InvariantCulture, out var c) ? c : 0;

            if (!refsByGuid.TryGetValue(guid, out var refs))
            {
                refs = new List<string>();
                refsByGuid[guid] = refs;
                elementMeta[guid] = (cls, storey.Length == 0 ? null : storey, conf);
            }

            if (itemRef.Length == 0)
            {
                // Scope gap: counted once per element, keyed by class.
                if (!unmapped.TryGetValue(cls, out var gap)) gap = (0, basis);
                unmapped[cls] = (gap.Count + 1, gap.Reason);
                continue;
            }

            refs.Add(itemRef);

            // An element is only as well-placed as its shakiest binding.
            var meta = elementMeta[guid];
            elementMeta[guid] = (meta.Cls, meta.Storey, Math.Min(meta.Conf, conf));

            var key = (cls, itemRef);
            if (!ruleCounts.TryGetValue(key, out var rule)) rule = (f[cRole].Trim(), basis, conf, 0);
            ruleCounts[key] = (rule.Role, rule.Basis, rule.Conf, rule.Count + 1);
        }

        var elements = refsByGuid
            .Select(kv => new MappedElement(
                kv.Key, elementMeta[kv.Key].Cls, elementMeta[kv.Key].Storey,
                kv.Value, kv.Value.Count == 0 ? 0 : elementMeta[kv.Key].Conf))
            .OrderBy(e => e.GlobalId, StringComparer.Ordinal)
            .ToList();

        var rules = ruleCounts
            .Select(kv => new MappingRule(kv.Key.Cls, kv.Key.Item, kv.Value.Role, kv.Value.Basis,
                kv.Value.Conf, kv.Value.Count))
            .OrderBy(r => r.BoqItemRef, StringComparer.Ordinal)
            .ToList();

        var gaps = unmapped
            .Select(kv => new UnmappedClass(kv.Key, kv.Value.Count, kv.Value.Reason))
            .OrderByDescending(u => u.ElementCount)
            .ToList();

        return new IfcElementMap(elements, rules, gaps);
    }

    /// <summary>
    /// Minimal RFC-4180 split — the Basis column carries commas inside quotes, so a naive
    /// <c>Split(',')</c> would shear every rationale in half.
    /// </summary>
    private static string[] SplitCsv(string line)
    {
        var outp = new List<string>();
        var cur = new System.Text.StringBuilder();
        bool quoted = false;

        for (int i = 0; i < line.Length; i++)
        {
            char ch = line[i];
            if (quoted)
            {
                if (ch == '"')
                {
                    if (i + 1 < line.Length && line[i + 1] == '"') { cur.Append('"'); i++; }
                    else quoted = false;
                }
                else cur.Append(ch);
            }
            else if (ch == '"') quoted = true;
            else if (ch == ',') { outp.Add(cur.ToString()); cur.Clear(); }
            else cur.Append(ch);
        }
        outp.Add(cur.ToString());
        return outp.ToArray();
    }
}
